//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 02:57:21 PM CET 
//


package limmen.kth.se.id2208.hw1.java_mappings.generated_pojos.employment_record;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the limmen.kth.se.id2208.hw1.java_mappings.generated_pojos.employment_record package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: limmen.kth.se.id2208.hw1.java_mappings.generated_pojos.employment_record
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmploymentRecord }
     * 
     */
    public EmploymentRecord createEmploymentRecord() {
        return new EmploymentRecord();
    }

    /**
     * Create an instance of {@link EmploymentRecord.EmploymentHistory }
     * 
     */
    public EmploymentRecord.EmploymentHistory createEmploymentRecordEmploymentHistory() {
        return new EmploymentRecord.EmploymentHistory();
    }

    /**
     * Create an instance of {@link EmploymentRecord.Employee }
     * 
     */
    public EmploymentRecord.Employee createEmploymentRecordEmployee() {
        return new EmploymentRecord.Employee();
    }

    /**
     * Create an instance of {@link EmploymentRecord.EmploymentHistory.Employment }
     * 
     */
    public EmploymentRecord.EmploymentHistory.Employment createEmploymentRecordEmploymentHistoryEmployment() {
        return new EmploymentRecord.EmploymentHistory.Employment();
    }

}
