
package kth.se.id2208.client.artifacts;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightTicketReservationPortType", targetNamespace = "http://flight_reservation")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightTicketReservationPortType {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<kth.se.id2208.client.artifacts.Itinerary>
     * @throws AuthorizationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItineraries", targetNamespace = "http://flight_reservation", className = "kth.se.id2208.client.artifacts.GetItineraries")
    @ResponseWrapper(localName = "getItinerariesResponse", targetNamespace = "http://flight_reservation", className = "kth.se.id2208.client.artifacts.GetItinerariesResponse")
    @Action(input = "http://flight_reservation/FlightTicketReservationPortType/getItinerariesRequest", output = "http://flight_reservation/FlightTicketReservationPortType/getItinerariesResponse", fault = {
        @FaultAction(className = AuthorizationException_Exception.class, value = "http://flight_reservation/FlightTicketReservationPortType/getItineraries/Fault/AuthorizationException")
    })
    public List<Itinerary> getItineraries(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws AuthorizationException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<kth.se.id2208.client.artifacts.Ticket>
     * @throws AuthorizationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableTickets", targetNamespace = "http://flight_reservation", className = "kth.se.id2208.client.artifacts.GetAvailableTickets")
    @ResponseWrapper(localName = "getAvailableTicketsResponse", targetNamespace = "http://flight_reservation", className = "kth.se.id2208.client.artifacts.GetAvailableTicketsResponse")
    @Action(input = "http://flight_reservation/FlightTicketReservationPortType/getAvailableTicketsRequest", output = "http://flight_reservation/FlightTicketReservationPortType/getAvailableTicketsResponse", fault = {
        @FaultAction(className = AuthorizationException_Exception.class, value = "http://flight_reservation/FlightTicketReservationPortType/getAvailableTickets/Fault/AuthorizationException")
    })
    public List<Ticket> getAvailableTickets(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Itinerary arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws AuthorizationException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<kth.se.id2208.client.artifacts.PriceEntry>
     * @throws AuthorizationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPriceList", targetNamespace = "http://flight_reservation", className = "kth.se.id2208.client.artifacts.GetPriceList")
    @ResponseWrapper(localName = "getPriceListResponse", targetNamespace = "http://flight_reservation", className = "kth.se.id2208.client.artifacts.GetPriceListResponse")
    @Action(input = "http://flight_reservation/FlightTicketReservationPortType/getPriceListRequest", output = "http://flight_reservation/FlightTicketReservationPortType/getPriceListResponse", fault = {
        @FaultAction(className = AuthorizationException_Exception.class, value = "http://flight_reservation/FlightTicketReservationPortType/getPriceList/Fault/AuthorizationException")
    })
    public List<PriceEntry> getPriceList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws AuthorizationException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns kth.se.id2208.client.artifacts.Receipt
     * @throws AuthorizationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookTickets", targetNamespace = "http://flight_reservation", className = "kth.se.id2208.client.artifacts.BookTickets")
    @ResponseWrapper(localName = "bookTicketsResponse", targetNamespace = "http://flight_reservation", className = "kth.se.id2208.client.artifacts.BookTicketsResponse")
    @Action(input = "http://flight_reservation/FlightTicketReservationPortType/bookTicketsRequest", output = "http://flight_reservation/FlightTicketReservationPortType/bookTicketsResponse", fault = {
        @FaultAction(className = AuthorizationException_Exception.class, value = "http://flight_reservation/FlightTicketReservationPortType/bookTickets/Fault/AuthorizationException")
    })
    public Receipt bookTickets(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Ticket> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws AuthorizationException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<kth.se.id2208.client.artifacts.PurchasedTicket>
     * @throws AuthorizationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "issueTickets", targetNamespace = "http://flight_reservation", className = "kth.se.id2208.client.artifacts.IssueTickets")
    @ResponseWrapper(localName = "issueTicketsResponse", targetNamespace = "http://flight_reservation", className = "kth.se.id2208.client.artifacts.IssueTicketsResponse")
    @Action(input = "http://flight_reservation/FlightTicketReservationPortType/issueTicketsRequest", output = "http://flight_reservation/FlightTicketReservationPortType/issueTicketsResponse", fault = {
        @FaultAction(className = AuthorizationException_Exception.class, value = "http://flight_reservation/FlightTicketReservationPortType/issueTickets/Fault/AuthorizationException")
    })
    public List<PurchasedTicket> issueTickets(
        @WebParam(name = "arg0", targetNamespace = "")
        Receipt arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws AuthorizationException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws AuthorizationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://flight_reservation", className = "kth.se.id2208.client.artifacts.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://flight_reservation", className = "kth.se.id2208.client.artifacts.LoginResponse")
    @Action(input = "http://flight_reservation/FlightTicketReservationPortType/loginRequest", output = "http://flight_reservation/FlightTicketReservationPortType/loginResponse", fault = {
        @FaultAction(className = AuthorizationException_Exception.class, value = "http://flight_reservation/FlightTicketReservationPortType/login/Fault/AuthorizationException")
    })
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws AuthorizationException_Exception
    ;

}
