//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 02:57:33 PM CET 
//


package limmen.kth.se.id2208.hw1.java_mappings.generated_pojos.short_cv;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PersonalInformation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FirstName">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="LastName">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CivicRegistrationNumber">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="\d{6}-\d{4}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Email">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[^@]+@[^\.]+\..+"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Skills">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Skill" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Preferences">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="JobInterest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="JobType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="permanent"/>
 *                         &lt;enumeration value="part time"/>
 *                         &lt;enumeration value="contract"/>
 *                         &lt;enumeration value="consult"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Locations">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MotivationLetter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "personalInformation",
    "skills",
    "preferences",
    "motivationLetter"
})
@XmlRootElement(name = "ShortCV", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class ShortCV {

    @XmlElement(name = "PersonalInformation", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ShortCV.PersonalInformation personalInformation;
    @XmlElement(name = "Skills", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ShortCV.Skills skills;
    @XmlElement(name = "Preferences", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ShortCV.Preferences preferences;
    @XmlElement(name = "MotivationLetter", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String motivationLetter;

    /**
     * Gets the value of the personalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ShortCV.PersonalInformation }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ShortCV.PersonalInformation getPersonalInformation() {
        return personalInformation;
    }

    /**
     * Sets the value of the personalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShortCV.PersonalInformation }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPersonalInformation(ShortCV.PersonalInformation value) {
        this.personalInformation = value;
    }

    /**
     * Gets the value of the skills property.
     * 
     * @return
     *     possible object is
     *     {@link ShortCV.Skills }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ShortCV.Skills getSkills() {
        return skills;
    }

    /**
     * Sets the value of the skills property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShortCV.Skills }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setSkills(ShortCV.Skills value) {
        this.skills = value;
    }

    /**
     * Gets the value of the preferences property.
     * 
     * @return
     *     possible object is
     *     {@link ShortCV.Preferences }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ShortCV.Preferences getPreferences() {
        return preferences;
    }

    /**
     * Sets the value of the preferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShortCV.Preferences }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPreferences(ShortCV.Preferences value) {
        this.preferences = value;
    }

    /**
     * Gets the value of the motivationLetter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getMotivationLetter() {
        return motivationLetter;
    }

    /**
     * Sets the value of the motivationLetter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setMotivationLetter(String value) {
        this.motivationLetter = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FirstName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="LastName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CivicRegistrationNumber">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="\d{6}-\d{4}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Email">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[^@]+@[^\.]+\..+"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firstName",
        "lastName",
        "city",
        "civicRegistrationNumber",
        "email"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class PersonalInformation {

        @XmlElement(name = "FirstName", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String firstName;
        @XmlElement(name = "LastName", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String lastName;
        @XmlElement(name = "City", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String city;
        @XmlElement(name = "CivicRegistrationNumber", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String civicRegistrationNumber;
        @XmlElement(name = "Email", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String email;

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the civicRegistrationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getCivicRegistrationNumber() {
            return civicRegistrationNumber;
        }

        /**
         * Sets the value of the civicRegistrationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setCivicRegistrationNumber(String value) {
            this.civicRegistrationNumber = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setEmail(String value) {
            this.email = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="JobInterest" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="JobType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="permanent"/>
     *               &lt;enumeration value="part time"/>
     *               &lt;enumeration value="contract"/>
     *               &lt;enumeration value="consult"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Locations">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jobInterest",
        "jobType",
        "locations"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class Preferences {

        @XmlElement(name = "JobInterest", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String jobInterest;
        @XmlElement(name = "JobType", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String jobType;
        @XmlElement(name = "Locations", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected ShortCV.Preferences.Locations locations;

        /**
         * Gets the value of the jobInterest property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getJobInterest() {
            return jobInterest;
        }

        /**
         * Sets the value of the jobInterest property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setJobInterest(String value) {
            this.jobInterest = value;
        }

        /**
         * Gets the value of the jobType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getJobType() {
            return jobType;
        }

        /**
         * Sets the value of the jobType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setJobType(String value) {
            this.jobType = value;
        }

        /**
         * Gets the value of the locations property.
         * 
         * @return
         *     possible object is
         *     {@link ShortCV.Preferences.Locations }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public ShortCV.Preferences.Locations getLocations() {
            return locations;
        }

        /**
         * Sets the value of the locations property.
         * 
         * @param value
         *     allowed object is
         *     {@link ShortCV.Preferences.Locations }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setLocations(ShortCV.Preferences.Locations value) {
            this.locations = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "location"
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public static class Locations {

            @XmlElement(name = "Location", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv", required = true)
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected List<String> location;

            /**
             * Gets the value of the location property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the location property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLocation().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public List<String> getLocation() {
                if (location == null) {
                    location = new ArrayList<String>();
                }
                return this.location;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Skill" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "skill"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class Skills {

        @XmlElement(name = "Skill", namespace = "http://www.limmen.kth.se.id2208.hw1.short_cv")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected List<String> skill;

        /**
         * Gets the value of the skill property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the skill property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSkill().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:33+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public List<String> getSkill() {
            if (skill == null) {
                skill = new ArrayList<String>();
            }
            return this.skill;
        }

    }

}
