
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlightTicketReservationServiceService", targetNamespace = "http://flight_reservation", wsdlLocation = "http://localhost:9000/bottom_up.FlightTicketReservationService?wsdl")
public class FlightTicketReservationServiceService
    extends Service
{

    private final static URL FLIGHTTICKETRESERVATIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FLIGHTTICKETRESERVATIONSERVICESERVICE_EXCEPTION;
    private final static QName FLIGHTTICKETRESERVATIONSERVICESERVICE_QNAME = new QName("http://flight_reservation", "FlightTicketReservationServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/bottom_up.FlightTicketReservationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTTICKETRESERVATIONSERVICESERVICE_WSDL_LOCATION = url;
        FLIGHTTICKETRESERVATIONSERVICESERVICE_EXCEPTION = e;
    }

    public FlightTicketReservationServiceService() {
        super(__getWsdlLocation(), FLIGHTTICKETRESERVATIONSERVICESERVICE_QNAME);
    }

    public FlightTicketReservationServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTTICKETRESERVATIONSERVICESERVICE_QNAME, features);
    }

    public FlightTicketReservationServiceService(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTTICKETRESERVATIONSERVICESERVICE_QNAME);
    }

    public FlightTicketReservationServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTTICKETRESERVATIONSERVICESERVICE_QNAME, features);
    }

    public FlightTicketReservationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightTicketReservationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightTicketReservationService
     */
    @WebEndpoint(name = "FlightTicketReservationServicePort")
    public FlightTicketReservationService getFlightTicketReservationServicePort() {
        return super.getPort(new QName("http://flight_reservation", "FlightTicketReservationServicePort"), FlightTicketReservationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightTicketReservationService
     */
    @WebEndpoint(name = "FlightTicketReservationServicePort")
    public FlightTicketReservationService getFlightTicketReservationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://flight_reservation", "FlightTicketReservationServicePort"), FlightTicketReservationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTTICKETRESERVATIONSERVICESERVICE_EXCEPTION!= null) {
            throw FLIGHTTICKETRESERVATIONSERVICESERVICE_EXCEPTION;
        }
        return FLIGHTTICKETRESERVATIONSERVICESERVICE_WSDL_LOCATION;
    }

}
