
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightTicketReservationService", targetNamespace = "http://flight_reservation")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightTicketReservationService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorldFrom", targetNamespace = "http://flight_reservation", className = "client.SayHelloWorldFrom")
    @ResponseWrapper(localName = "sayHelloWorldFromResponse", targetNamespace = "http://flight_reservation", className = "client.SayHelloWorldFromResponse")
    @Action(input = "http://flight_reservation/FlightTicketReservationService/sayHelloWorldFromRequest", output = "http://flight_reservation/FlightTicketReservationService/sayHelloWorldFromResponse")
    public String sayHelloWorldFrom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws AuthorizationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://flight_reservation", className = "client.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://flight_reservation", className = "client.LoginResponse")
    @Action(input = "http://flight_reservation/FlightTicketReservationService/loginRequest", output = "http://flight_reservation/FlightTicketReservationService/loginResponse", fault = {
        @FaultAction(className = AuthorizationException_Exception.class, value = "http://flight_reservation/FlightTicketReservationService/login/Fault/AuthorizationException")
    })
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws AuthorizationException_Exception
    ;

}
