//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 02:57:33 PM CET 
//


package limmen.kth.se.id2208.hw1.parsing.generated_pojos.short_cv;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the limmen.kth.se.id2208.hw1.parsing.generated_pojos.short_cv package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: limmen.kth.se.id2208.hw1.parsing.generated_pojos.short_cv
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShortCV }
     * 
     */
    public ShortCV createShortCV() {
        return new ShortCV();
    }

    /**
     * Create an instance of {@link ShortCV.Preferences }
     * 
     */
    public ShortCV.Preferences createShortCVPreferences() {
        return new ShortCV.Preferences();
    }

    /**
     * Create an instance of {@link ShortCV.PersonalInformation }
     * 
     */
    public ShortCV.PersonalInformation createShortCVPersonalInformation() {
        return new ShortCV.PersonalInformation();
    }

    /**
     * Create an instance of {@link ShortCV.Skills }
     * 
     */
    public ShortCV.Skills createShortCVSkills() {
        return new ShortCV.Skills();
    }

    /**
     * Create an instance of {@link ShortCV.Preferences.Locations }
     * 
     */
    public ShortCV.Preferences.Locations createShortCVPreferencesLocations() {
        return new ShortCV.Preferences.Locations();
    }

}
