//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 08:05:22 PM CET 
//


package limmen.kth.se.id2208.hw1.parsing.generated_pojos.application_profile;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Person">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FirstName">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="LastName">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CivicRegistrationNumber">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="\d{6}-\d{4}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Preferences">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="JobInterest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="JobType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="permanent"/>
 *                         &lt;enumeration value="part time"/>
 *                         &lt;enumeration value="contract"/>
 *                         &lt;enumeration value="consult"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Locations">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MotivationLetter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Degrees">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Degree" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DateOfCompletion" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="Credits">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *                                   &lt;minInclusive value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="GPA">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="5"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="WorkingExperience">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Employment" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="Company">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Name">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;minLength value="1"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="About" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "person",
    "preferences",
    "motivationLetter",
    "degrees",
    "workingExperience"
})
@XmlRootElement(name = "ApplicationProfile", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class ApplicationProfile {

    @XmlElement(name = "Person", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ApplicationProfile.Person person;
    @XmlElement(name = "Preferences", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ApplicationProfile.Preferences preferences;
    @XmlElement(name = "MotivationLetter", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String motivationLetter;
    @XmlElement(name = "Degrees", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ApplicationProfile.Degrees degrees;
    @XmlElement(name = "WorkingExperience", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected ApplicationProfile.WorkingExperience workingExperience;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationProfile.Person }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ApplicationProfile.Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationProfile.Person }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPerson(ApplicationProfile.Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the preferences property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationProfile.Preferences }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ApplicationProfile.Preferences getPreferences() {
        return preferences;
    }

    /**
     * Sets the value of the preferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationProfile.Preferences }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPreferences(ApplicationProfile.Preferences value) {
        this.preferences = value;
    }

    /**
     * Gets the value of the motivationLetter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getMotivationLetter() {
        return motivationLetter;
    }

    /**
     * Sets the value of the motivationLetter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setMotivationLetter(String value) {
        this.motivationLetter = value;
    }

    /**
     * Gets the value of the degrees property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationProfile.Degrees }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ApplicationProfile.Degrees getDegrees() {
        return degrees;
    }

    /**
     * Sets the value of the degrees property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationProfile.Degrees }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDegrees(ApplicationProfile.Degrees value) {
        this.degrees = value;
    }

    /**
     * Gets the value of the workingExperience property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationProfile.WorkingExperience }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public ApplicationProfile.WorkingExperience getWorkingExperience() {
        return workingExperience;
    }

    /**
     * Sets the value of the workingExperience property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationProfile.WorkingExperience }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setWorkingExperience(ApplicationProfile.WorkingExperience value) {
        this.workingExperience = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Degree" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Name">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DateOfCompletion" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="Credits">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
     *                         &lt;minInclusive value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="GPA">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="5"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "degree"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class Degrees {

        @XmlElement(name = "Degree", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected List<ApplicationProfile.Degrees.Degree> degree;

        /**
         * Gets the value of the degree property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the degree property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDegree().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ApplicationProfile.Degrees.Degree }
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public List<ApplicationProfile.Degrees.Degree> getDegree() {
            if (degree == null) {
                degree = new ArrayList<ApplicationProfile.Degrees.Degree>();
            }
            return this.degree;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Name">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DateOfCompletion" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="Credits">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
         *               &lt;minInclusive value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="GPA">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="5"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "dateOfCompletion",
            "credits",
            "gpa"
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public static class Degree {

            @XmlElement(name = "Name", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected String name;
            @XmlElement(name = "DateOfCompletion", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
            @XmlSchemaType(name = "date")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected XMLGregorianCalendar dateOfCompletion;
            @XmlElement(name = "Credits", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected float credits;
            @XmlElement(name = "GPA", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected float gpa;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the dateOfCompletion property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public XMLGregorianCalendar getDateOfCompletion() {
                return dateOfCompletion;
            }

            /**
             * Sets the value of the dateOfCompletion property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setDateOfCompletion(XMLGregorianCalendar value) {
                this.dateOfCompletion = value;
            }

            /**
             * Gets the value of the credits property.
             * 
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public float getCredits() {
                return credits;
            }

            /**
             * Sets the value of the credits property.
             * 
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setCredits(float value) {
                this.credits = value;
            }

            /**
             * Gets the value of the gpa property.
             * 
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public float getGPA() {
                return gpa;
            }

            /**
             * Sets the value of the gpa property.
             * 
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setGPA(float value) {
                this.gpa = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FirstName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="LastName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CivicRegistrationNumber">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="\d{6}-\d{4}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firstName",
        "lastName",
        "civicRegistrationNumber"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class Person {

        @XmlElement(name = "FirstName", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String firstName;
        @XmlElement(name = "LastName", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String lastName;
        @XmlElement(name = "CivicRegistrationNumber", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String civicRegistrationNumber;

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the civicRegistrationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getCivicRegistrationNumber() {
            return civicRegistrationNumber;
        }

        /**
         * Sets the value of the civicRegistrationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setCivicRegistrationNumber(String value) {
            this.civicRegistrationNumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="JobInterest" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="JobType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="permanent"/>
     *               &lt;enumeration value="part time"/>
     *               &lt;enumeration value="contract"/>
     *               &lt;enumeration value="consult"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Locations">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jobInterest",
        "jobType",
        "locations"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class Preferences {

        @XmlElement(name = "JobInterest", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String jobInterest;
        @XmlElement(name = "JobType", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String jobType;
        @XmlElement(name = "Locations", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected ApplicationProfile.Preferences.Locations locations;

        /**
         * Gets the value of the jobInterest property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getJobInterest() {
            return jobInterest;
        }

        /**
         * Sets the value of the jobInterest property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setJobInterest(String value) {
            this.jobInterest = value;
        }

        /**
         * Gets the value of the jobType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getJobType() {
            return jobType;
        }

        /**
         * Sets the value of the jobType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setJobType(String value) {
            this.jobType = value;
        }

        /**
         * Gets the value of the locations property.
         * 
         * @return
         *     possible object is
         *     {@link ApplicationProfile.Preferences.Locations }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public ApplicationProfile.Preferences.Locations getLocations() {
            return locations;
        }

        /**
         * Sets the value of the locations property.
         * 
         * @param value
         *     allowed object is
         *     {@link ApplicationProfile.Preferences.Locations }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setLocations(ApplicationProfile.Preferences.Locations value) {
            this.locations = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "location"
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public static class Locations {

            @XmlElement(name = "Location", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected List<String> location;

            /**
             * Gets the value of the location property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the location property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLocation().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public List<String> getLocation() {
                if (location == null) {
                    location = new ArrayList<String>();
                }
                return this.location;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Employment" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="Company">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Name">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="About" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "employment"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class WorkingExperience {

        @XmlElement(name = "Employment", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected List<ApplicationProfile.WorkingExperience.Employment> employment;

        /**
         * Gets the value of the employment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the employment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEmployment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ApplicationProfile.WorkingExperience.Employment }
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public List<ApplicationProfile.WorkingExperience.Employment> getEmployment() {
            if (employment == null) {
                employment = new ArrayList<ApplicationProfile.WorkingExperience.Employment>();
            }
            return this.employment;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="Company">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Name">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;minLength value="1"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="About" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "startDate",
            "endDate",
            "company",
            "title"
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public static class Employment {

            @XmlElement(name = "StartDate", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
            @XmlSchemaType(name = "date")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected XMLGregorianCalendar startDate;
            @XmlElement(name = "EndDate", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
            @XmlSchemaType(name = "date")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected XMLGregorianCalendar endDate;
            @XmlElement(name = "Company", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected ApplicationProfile.WorkingExperience.Employment.Company company;
            @XmlElement(name = "Title", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected String title;

            /**
             * Gets the value of the startDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public XMLGregorianCalendar getStartDate() {
                return startDate;
            }

            /**
             * Sets the value of the startDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setStartDate(XMLGregorianCalendar value) {
                this.startDate = value;
            }

            /**
             * Gets the value of the endDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public XMLGregorianCalendar getEndDate() {
                return endDate;
            }

            /**
             * Sets the value of the endDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setEndDate(XMLGregorianCalendar value) {
                this.endDate = value;
            }

            /**
             * Gets the value of the company property.
             * 
             * @return
             *     possible object is
             *     {@link ApplicationProfile.WorkingExperience.Employment.Company }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public ApplicationProfile.WorkingExperience.Employment.Company getCompany() {
                return company;
            }

            /**
             * Sets the value of the company property.
             * 
             * @param value
             *     allowed object is
             *     {@link ApplicationProfile.WorkingExperience.Employment.Company }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setCompany(ApplicationProfile.WorkingExperience.Employment.Company value) {
                this.company = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setTitle(String value) {
                this.title = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Name">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;minLength value="1"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="About" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "about",
                "website"
            })
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public static class Company {

                @XmlElement(name = "Name", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
                protected String name;
                @XmlElement(name = "About", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
                protected String about;
                @XmlElement(name = "Website", namespace = "http://www.limmen.kth.se.id2208.hw1.application_profile", required = true)
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
                protected String website;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the about property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public String getAbout() {
                    return about;
                }

                /**
                 * Sets the value of the about property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public void setAbout(String value) {
                    this.about = value;
                }

                /**
                 * Gets the value of the website property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public String getWebsite() {
                    return website;
                }

                /**
                 * Sets the value of the website property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:05:22+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public void setWebsite(String value) {
                    this.website = value;
                }

            }

        }

    }

}
