//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 08:05:22 PM CET 
//


package limmen.kth.se.id2208.hw1.parsing.generated_pojos.application_profile;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the limmen.kth.se.id2208.hw1.parsing.generated_pojos.application_profile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: limmen.kth.se.id2208.hw1.parsing.generated_pojos.application_profile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ApplicationProfile }
     * 
     */
    public ApplicationProfile createApplicationProfile() {
        return new ApplicationProfile();
    }

    /**
     * Create an instance of {@link ApplicationProfile.WorkingExperience }
     * 
     */
    public ApplicationProfile.WorkingExperience createApplicationProfileWorkingExperience() {
        return new ApplicationProfile.WorkingExperience();
    }

    /**
     * Create an instance of {@link ApplicationProfile.WorkingExperience.Employment }
     * 
     */
    public ApplicationProfile.WorkingExperience.Employment createApplicationProfileWorkingExperienceEmployment() {
        return new ApplicationProfile.WorkingExperience.Employment();
    }

    /**
     * Create an instance of {@link ApplicationProfile.Degrees }
     * 
     */
    public ApplicationProfile.Degrees createApplicationProfileDegrees() {
        return new ApplicationProfile.Degrees();
    }

    /**
     * Create an instance of {@link ApplicationProfile.Preferences }
     * 
     */
    public ApplicationProfile.Preferences createApplicationProfilePreferences() {
        return new ApplicationProfile.Preferences();
    }

    /**
     * Create an instance of {@link ApplicationProfile.Person }
     * 
     */
    public ApplicationProfile.Person createApplicationProfilePerson() {
        return new ApplicationProfile.Person();
    }

    /**
     * Create an instance of {@link ApplicationProfile.WorkingExperience.Employment.Company }
     * 
     */
    public ApplicationProfile.WorkingExperience.Employment.Company createApplicationProfileWorkingExperienceEmploymentCompany() {
        return new ApplicationProfile.WorkingExperience.Employment.Company();
    }

    /**
     * Create an instance of {@link ApplicationProfile.Degrees.Degree }
     * 
     */
    public ApplicationProfile.Degrees.Degree createApplicationProfileDegreesDegree() {
        return new ApplicationProfile.Degrees.Degree();
    }

    /**
     * Create an instance of {@link ApplicationProfile.Preferences.Locations }
     * 
     */
    public ApplicationProfile.Preferences.Locations createApplicationProfilePreferencesLocations() {
        return new ApplicationProfile.Preferences.Locations();
    }

}
