//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 02:57:07 PM CET 
//


package limmen.kth.se.id2208.hw1.java_mappings.generated_pojos.company_info;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Company" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Anno" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *                   &lt;element name="About" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Contact">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Phone" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;pattern value="^(\+[1-9][0-9]*(\([0-9]*\)|-[0-9]*-))?[0]?[1-9][0-9\- ]*$"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Email">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;pattern value="[^@]+@[^\.]+\..+"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "company"
})
@XmlRootElement(name = "CompaniesInfo", namespace = "http://www.limmen.kth.se.id2208.hw1.company_info")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class CompaniesInfo {

    @XmlElement(name = "Company", namespace = "http://www.limmen.kth.se.id2208.hw1.company_info")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<CompaniesInfo.Company> company;

    /**
     * Gets the value of the company property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the company property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompany().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompaniesInfo.Company }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<CompaniesInfo.Company> getCompany() {
        if (company == null) {
            company = new ArrayList<CompaniesInfo.Company>();
        }
        return this.company;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Anno" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
     *         &lt;element name="About" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Contact">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Phone" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="^(\+[1-9][0-9]*(\([0-9]*\)|-[0-9]*-))?[0]?[1-9][0-9\- ]*$"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Email">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="[^@]+@[^\.]+\..+"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "address",
        "anno",
        "about",
        "contact",
        "website"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class Company {

        @XmlElement(name = "Name", namespace = "http://www.limmen.kth.se.id2208.hw1.company_info", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String name;
        @XmlElement(name = "Address", namespace = "http://www.limmen.kth.se.id2208.hw1.company_info", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String address;
        @XmlElement(name = "Anno", namespace = "http://www.limmen.kth.se.id2208.hw1.company_info", required = true)
        @XmlSchemaType(name = "gYear")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected XMLGregorianCalendar anno;
        @XmlElement(name = "About", namespace = "http://www.limmen.kth.se.id2208.hw1.company_info", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String about;
        @XmlElement(name = "Contact", namespace = "http://www.limmen.kth.se.id2208.hw1.company_info", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected CompaniesInfo.Company.Contact contact;
        @XmlElement(name = "Website", namespace = "http://www.limmen.kth.se.id2208.hw1.company_info", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String website;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setAddress(String value) {
            this.address = value;
        }

        /**
         * Gets the value of the anno property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public XMLGregorianCalendar getAnno() {
            return anno;
        }

        /**
         * Sets the value of the anno property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setAnno(XMLGregorianCalendar value) {
            this.anno = value;
        }

        /**
         * Gets the value of the about property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getAbout() {
            return about;
        }

        /**
         * Sets the value of the about property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setAbout(String value) {
            this.about = value;
        }

        /**
         * Gets the value of the contact property.
         * 
         * @return
         *     possible object is
         *     {@link CompaniesInfo.Company.Contact }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public CompaniesInfo.Company.Contact getContact() {
            return contact;
        }

        /**
         * Sets the value of the contact property.
         * 
         * @param value
         *     allowed object is
         *     {@link CompaniesInfo.Company.Contact }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setContact(CompaniesInfo.Company.Contact value) {
            this.contact = value;
        }

        /**
         * Gets the value of the website property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getWebsite() {
            return website;
        }

        /**
         * Sets the value of the website property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setWebsite(String value) {
            this.website = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Phone" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="^(\+[1-9][0-9]*(\([0-9]*\)|-[0-9]*-))?[0]?[1-9][0-9\- ]*$"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Email">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="[^@]+@[^\.]+\..+"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "phone",
            "email"
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public static class Contact {

            @XmlElement(name = "Phone", namespace = "http://www.limmen.kth.se.id2208.hw1.company_info")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected String phone;
            @XmlElement(name = "Email", namespace = "http://www.limmen.kth.se.id2208.hw1.company_info", required = true)
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected String email;

            /**
             * Gets the value of the phone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public String getPhone() {
                return phone;
            }

            /**
             * Sets the value of the phone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setPhone(String value) {
                this.phone = value;
            }

            /**
             * Gets the value of the email property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public String getEmail() {
                return email;
            }

            /**
             * Sets the value of the email property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T02:57:07+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setEmail(String value) {
                this.email = value;
            }

        }

    }

}
