//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 02:57:07 PM CET 
//


package limmen.kth.se.id2208.hw1.java_mappings.generated_pojos.company_info;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the limmen.kth.se.id2208.hw1.java_mappings.generated_pojos.company_info package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: limmen.kth.se.id2208.hw1.java_mappings.generated_pojos.company_info
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CompaniesInfo }
     * 
     */
    public CompaniesInfo createCompaniesInfo() {
        return new CompaniesInfo();
    }

    /**
     * Create an instance of {@link CompaniesInfo.Company }
     * 
     */
    public CompaniesInfo.Company createCompaniesInfoCompany() {
        return new CompaniesInfo.Company();
    }

    /**
     * Create an instance of {@link CompaniesInfo.Company.Contact }
     * 
     */
    public CompaniesInfo.Company.Contact createCompaniesInfoCompanyContact() {
        return new CompaniesInfo.Company.Contact();
    }

}
