//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.27 at 11:17:15 AM CET 
//


package limmen.kth.se.id2208.hw1.parsing.generated_pojos.transcript;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the limmen.kth.se.id2208.hw1.parsing.generated_pojos.transcript package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Credits_QNAME = new QName("http://www.limmen.kth.se.id2208.hw1.transcript", "Credits");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: limmen.kth.se.id2208.hw1.parsing.generated_pojos.transcript
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Transcript }
     * 
     */
    public Transcript createTranscript() {
        return new Transcript();
    }

    /**
     * Create an instance of {@link Transcript.Courses }
     * 
     */
    public Transcript.Courses createTranscriptCourses() {
        return new Transcript.Courses();
    }

    /**
     * Create an instance of {@link Transcript.Degrees }
     * 
     */
    public Transcript.Degrees createTranscriptDegrees() {
        return new Transcript.Degrees();
    }

    /**
     * Create an instance of {@link Transcript.Student }
     * 
     */
    public Transcript.Student createTranscriptStudent() {
        return new Transcript.Student();
    }

    /**
     * Create an instance of {@link Transcript.Courses.Course }
     * 
     */
    public Transcript.Courses.Course createTranscriptCoursesCourse() {
        return new Transcript.Courses.Course();
    }

    /**
     * Create an instance of {@link Transcript.Degrees.Degree }
     * 
     */
    public Transcript.Degrees.Degree createTranscriptDegreesDegree() {
        return new Transcript.Degrees.Degree();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", name = "Credits")
    public JAXBElement<Float> createCredits(Float value) {
        return new JAXBElement<Float>(_Credits_QNAME, Float.class, null, value);
    }

}
