//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 08:06:01 PM CET 
//


package limmen.kth.se.id2208.hw1.parsing.generated_pojos.transcript;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Student">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FirstName">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="LastName">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CivicRegistrationNumber">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="\d{6}-\d{4}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Degrees">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Degree" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="DateOfIssue" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="DateOfCompletion" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element ref="{http://www.limmen.kth.se.id2208.hw1.transcript}Credits"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="degreeId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Courses">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Course" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Code">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;pattern value="[A-Z]{2}[0-9]{4}"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element ref="{http://www.limmen.kth.se.id2208.hw1.transcript}Credits"/>
 *                             &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="Grade">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;pattern value="[A-F]"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="degree" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="universityName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="generationDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "student",
    "degrees",
    "courses"
})
@XmlRootElement(name = "Transcript", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class Transcript {

    @XmlElement(name = "Student", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Transcript.Student student;
    @XmlElement(name = "Degrees", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Transcript.Degrees degrees;
    @XmlElement(name = "Courses", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Transcript.Courses courses;
    @XmlAttribute(name = "universityName", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String universityName;
    @XmlAttribute(name = "generationDate", required = true)
    @XmlSchemaType(name = "date")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected XMLGregorianCalendar generationDate;

    /**
     * Gets the value of the student property.
     * 
     * @return
     *     possible object is
     *     {@link Transcript.Student }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Transcript.Student getStudent() {
        return student;
    }

    /**
     * Sets the value of the student property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transcript.Student }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setStudent(Transcript.Student value) {
        this.student = value;
    }

    /**
     * Gets the value of the degrees property.
     * 
     * @return
     *     possible object is
     *     {@link Transcript.Degrees }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Transcript.Degrees getDegrees() {
        return degrees;
    }

    /**
     * Sets the value of the degrees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transcript.Degrees }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDegrees(Transcript.Degrees value) {
        this.degrees = value;
    }

    /**
     * Gets the value of the courses property.
     * 
     * @return
     *     possible object is
     *     {@link Transcript.Courses }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Transcript.Courses getCourses() {
        return courses;
    }

    /**
     * Sets the value of the courses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transcript.Courses }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setCourses(Transcript.Courses value) {
        this.courses = value;
    }

    /**
     * Gets the value of the universityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getUniversityName() {
        return universityName;
    }

    /**
     * Sets the value of the universityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setUniversityName(String value) {
        this.universityName = value;
    }

    /**
     * Gets the value of the generationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public XMLGregorianCalendar getGenerationDate() {
        return generationDate;
    }

    /**
     * Sets the value of the generationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setGenerationDate(XMLGregorianCalendar value) {
        this.generationDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Course" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Code">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="[A-Z]{2}[0-9]{4}"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element ref="{http://www.limmen.kth.se.id2208.hw1.transcript}Credits"/>
     *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="Grade">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="[A-F]"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="degree" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "course"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class Courses {

        @XmlElement(name = "Course", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected List<Transcript.Courses.Course> course;

        /**
         * Gets the value of the course property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the course property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCourse().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Transcript.Courses.Course }
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public List<Transcript.Courses.Course> getCourse() {
            if (course == null) {
                course = new ArrayList<Transcript.Courses.Course>();
            }
            return this.course;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Code">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="[A-Z]{2}[0-9]{4}"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element ref="{http://www.limmen.kth.se.id2208.hw1.transcript}Credits"/>
         *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="Grade">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="[A-F]"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="degree" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "code",
            "credits",
            "date",
            "grade"
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public static class Course {

            @XmlElement(name = "Name", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected String name;
            @XmlElement(name = "Code", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected String code;
            @XmlElement(name = "Credits", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected float credits;
            @XmlElement(name = "Date", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
            @XmlSchemaType(name = "date")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected XMLGregorianCalendar date;
            @XmlElement(name = "Grade", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected String grade;
            @XmlAttribute(name = "degree")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected String degree;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the credits property.
             * 
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public float getCredits() {
                return credits;
            }

            /**
             * Sets the value of the credits property.
             * 
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setCredits(float value) {
                this.credits = value;
            }

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public XMLGregorianCalendar getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setDate(XMLGregorianCalendar value) {
                this.date = value;
            }

            /**
             * Gets the value of the grade property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public String getGrade() {
                return grade;
            }

            /**
             * Sets the value of the grade property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setGrade(String value) {
                this.grade = value;
            }

            /**
             * Gets the value of the degree property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public String getDegree() {
                return degree;
            }

            /**
             * Sets the value of the degree property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setDegree(String value) {
                this.degree = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Degree" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="DateOfIssue" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="DateOfCompletion" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element ref="{http://www.limmen.kth.se.id2208.hw1.transcript}Credits"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="degreeId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "degree"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class Degrees {

        @XmlElement(name = "Degree", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected List<Transcript.Degrees.Degree> degree;

        /**
         * Gets the value of the degree property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the degree property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDegree().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Transcript.Degrees.Degree }
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public List<Transcript.Degrees.Degree> getDegree() {
            if (degree == null) {
                degree = new ArrayList<Transcript.Degrees.Degree>();
            }
            return this.degree;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="DateOfIssue" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="DateOfCompletion" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element ref="{http://www.limmen.kth.se.id2208.hw1.transcript}Credits"/>
         *       &lt;/sequence>
         *       &lt;attribute name="degreeId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "startDate",
            "dateOfIssue",
            "dateOfCompletion",
            "credits"
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public static class Degree {

            @XmlElement(name = "Name", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected String name;
            @XmlElement(name = "StartDate", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
            @XmlSchemaType(name = "date")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected XMLGregorianCalendar startDate;
            @XmlElement(name = "DateOfIssue", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
            @XmlSchemaType(name = "date")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected XMLGregorianCalendar dateOfIssue;
            @XmlElement(name = "DateOfCompletion", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
            @XmlSchemaType(name = "date")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected XMLGregorianCalendar dateOfCompletion;
            @XmlElement(name = "Credits", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected float credits;
            @XmlAttribute(name = "degreeId", required = true)
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected String degreeId;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the startDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public XMLGregorianCalendar getStartDate() {
                return startDate;
            }

            /**
             * Sets the value of the startDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setStartDate(XMLGregorianCalendar value) {
                this.startDate = value;
            }

            /**
             * Gets the value of the dateOfIssue property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public XMLGregorianCalendar getDateOfIssue() {
                return dateOfIssue;
            }

            /**
             * Sets the value of the dateOfIssue property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setDateOfIssue(XMLGregorianCalendar value) {
                this.dateOfIssue = value;
            }

            /**
             * Gets the value of the dateOfCompletion property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public XMLGregorianCalendar getDateOfCompletion() {
                return dateOfCompletion;
            }

            /**
             * Sets the value of the dateOfCompletion property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setDateOfCompletion(XMLGregorianCalendar value) {
                this.dateOfCompletion = value;
            }

            /**
             * Gets the value of the credits property.
             * 
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public float getCredits() {
                return credits;
            }

            /**
             * Sets the value of the credits property.
             * 
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setCredits(float value) {
                this.credits = value;
            }

            /**
             * Gets the value of the degreeId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public String getDegreeId() {
                return degreeId;
            }

            /**
             * Sets the value of the degreeId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setDegreeId(String value) {
                this.degreeId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FirstName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="LastName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CivicRegistrationNumber">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="\d{6}-\d{4}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firstName",
        "lastName",
        "civicRegistrationNumber"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class Student {

        @XmlElement(name = "FirstName", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String firstName;
        @XmlElement(name = "LastName", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String lastName;
        @XmlElement(name = "CivicRegistrationNumber", namespace = "http://www.limmen.kth.se.id2208.hw1.transcript", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected String civicRegistrationNumber;

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the civicRegistrationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public String getCivicRegistrationNumber() {
            return civicRegistrationNumber;
        }

        /**
         * Sets the value of the civicRegistrationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2017-01-26T08:06:01+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setCivicRegistrationNumber(String value) {
            this.civicRegistrationNumber = value;
        }

    }

}
